## Q1. For all citations, what is the mean violation fine?

In [203]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [204]:
citation = pd.read_csv('./Parking_Citations.csv')
cite2 = citation.copy()
cite2.head()

/Users/satavisha/anaconda3/envs/py3env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (2,17,18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Citation,Tag,ExpMM,ExpYY,State,Make,Address,ViolCode,Description,ViolFine,...,Balance,PenaltyDate,OpenFine,OpenPenalty,NoticeDate,ImportDate,Neighborhood,PoliceDistrict,CouncilDistrict,Location
0,82691651,69943CF,04,19.0,MD,MAZD,1300 BLK EAST NORTHERN PKWY WB,32,Fixed Speed Camera,40.0,...,0.0,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"1300 BLK EAST NORTHERN PKWY\nWB Baltimore, MD\..."
1,85937226,T720887,12,18.0,MD,ACUR,300 BLK NORTH BEND RD SB,32,Fixed Speed Camera,40.0,...,40.0,NaN,0.0,0.0,NaN,01/03/2019 04:33:00 AM,NaN,NaN,NaN,NaN
2,82691115,5BA2678,03,19.0,MD,TOYT,5000 BLK ROLAND AVE NB,32,Fixed Speed Camera,40.0,...,0.0,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"5000 BLK ROLAND AVE\nNB Baltimore, MD\n(39.353..."
3,82694689,5BT8544,01,18.0,MD,FORD,2400 BLK ERDMAN AVE NB,32,Fixed Speed Camera,40.0,...,0.0,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"2400 BLK ERDMAN AVE\nNB Baltimore, MD\n(39.325..."
4,82691214,1BV0537,11,18.0,MD,SUBA,1300 BLK WEST COLD SPRING LN W,32,Fixed Speed Camera,40.0,...,0.0,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"1300 BLK WEST COLD SPRING LN W\nBaltimore, MD\..."

In [206]:
cite2.shape

(3385279, 21)

In [207]:
dir(cite2)

['Address',
 'Balance',
 'Citation',
 'CouncilDistrict',
 'Description',
 'ExpMM',
 'ExpYY',
 'ImportDate',
 'Location',
 'Make',
 'Neighborhood',
 'NoticeDate',
 'OpenFine',
 'OpenPenalty',
 'PenaltyDate',
 'PoliceDistrict',
 'State',
 'T',
 'Tag',
 'ViolCode',
 'ViolDate',
 'ViolFine',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_space_character_free_column_resolvers',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_frame',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [208]:
#citation.describe

In [209]:
cite2.columns

Index(['Citation', 'Tag', 'ExpMM', 'ExpYY', 'State', 'Make', 'Address',
       'ViolCode', 'Description', 'ViolFine', 'ViolDate', 'Balance',
       'PenaltyDate', 'OpenFine', 'OpenPenalty', 'NoticeDate', 'ImportDate',
       'Neighborhood', 'PoliceDistrict', 'CouncilDistrict', 'Location'],
      dtype='object')

In [210]:
cite2.dtypes

Citation             int64
Tag                 object
ExpMM               object
ExpYY              float64
State               object
Make                object
Address             object
ViolCode             int64
Description         object
ViolFine           float64
ViolDate            object
Balance            float64
PenaltyDate        float64
OpenFine           float64
OpenPenalty        float64
NoticeDate          object
ImportDate          object
Neighborhood        object
PoliceDistrict      object
CouncilDistrict    float64
Location            object
dtype: object

In [211]:
cite2.loc[:, 'ViolFine'].mean()

49.897334015896476

## Looking only at vehicles that have open penalty fees, what dollar amount is the 81st percentile of that group?

In [212]:
op_over_0 = cite2[cite2.OpenPenalty > 0.0]

In [213]:
op_over_0['OpenPenalty'].quantile(0.81)

480.0

## Find all citations where the police district has been given. Next, determine which district has the highest mean violation fine. What is that mean violation fine? Keep in mind that Baltimore is divided into nine police districts, so clean the data accordingly.

In [214]:
pol_dis = cite2[cite2['PoliceDistrict'].notna()]
pol_dis

,Citation,Tag,ExpMM,ExpYY,State,Make,Address,ViolCode,Description,ViolFine,...,Balance,PenaltyDate,OpenFine,OpenPenalty,NoticeDate,ImportDate,Neighborhood,PoliceDistrict,CouncilDistrict,Location
434,31807,9AE0437,08,12.0,MD,HOND,600 AISQUITH ST,18,All Other Parking Meter Violations,32.0,...,357.0,NaN,32.0,300.0,09/18/2012,04/09/2014 04:01:00 AM,Oldtown,Eastern,12.0,"600 AISQUITH ST\nBaltimore, MD"
435,31815,3AS5633,06,12.0,MD,FORD,600 AISQUITH ST,18,All Other Parking Meter Violations,32.0,...,332.0,NaN,32.0,300.0,09/26/2012,04/09/2014 04:01:00 AM,Oldtown,Eastern,12.0,"600 AISQUITH ST\nBaltimore, MD"
519,5044608,7DC3668,01,18.0,MD,NISS,509 N GILMOR ST,22,Expired Tags,32.0,...,0.0,NaN,32.0,0.0,NaN,05/15/2018 04:18:00 AM,Harlem Park,Western,9.0,"(39.29431651, -76.6424061)"
1242,64824,T223430T,12,11.0,MD,CADI,2527 LOYOLA SOUTHWAY,22,Expired Tags,32.0,...,32.0,NaN,32.0,0.0,NaN,05/07/2013 10:41:00 AM,Greenspring,Northern,6.0,"2527 LOYOLA\nSOUTHWAY Baltimore, MD"
1582,4988912,3CL1965,08,18.0,MD,CHEV,1200 BOLTON ST,17,Less Than 15 feet from Fire Hydrant,77.0,...,0.0,NaN,77.0,0.0,NaN,03/23/2018 04:02:00 AM,Bolton Hill,Central,11.0,"1200 BOLTON ST\nBaltimore, MD\n(39.304625, -76..."
1585,5037933,4DD9398,01,20.0,MD,GMC,400 S MACON ST,12,No Stopping/Standing Not Tow-Away Zone,32.0,...,0.0,NaN,32.0,0.0,NaN,04/06/2018 04:02:00 AM,Greektown,Southeastern,1.0,"400 S MACON ST\nBaltimore, MD\n(39.287927, -76..."
1595,21971684,54086M9,03,14.0,MD,TOYOT,700 ALICEANNA ST,12,No Stopping/Standing Not Tow-Away Zone,32.0,...,357.0,NaN,32.0,300.0,12/04/2013,07/09/2015 04:02:00 AM,Inner Harbor,Southeastern,1.0,"700 ALICEANNA ST\nBaltimore, MD\n(39.283111, -..."
1685,20225108,504M906,03,13.0,MD,JEEP,1200 GITTINGS AVE,22,Expired Tags,32.0,...,357.0,NaN,32.0,300.0,04/24/2013,11/12/2014 04:02:00 AM,Idlewood,Notheastern,4.0,"1200 GITTINGS AVE\nBaltimore, MD\n(39.370213, ..."
2742,63156484,62401CG,07,18.0,MD,BMW,3400 ELMORA AVE,19,Exceeding 48 Hours,32.0,...,0.0,NaN,32.0,0.0,NaN,05/01/2018 04:02:00 AM,Four By Four,Notheastern,13.0,"3400 ELMORA AVE\nBaltimore, MD\n(39.315891, -7..."
3392,210831,9AK3309,10,13.0,MD,DODG,301 LIGHT ST,5,Obstruct/Impeding Movement of Pedestrian,77.0,...,852.0,NaN,77.0,775.0,09/20/2012,08/09/2016 04:02:00 AM,Inner Harbor,Central,11.0,"301 LIGHT ST\nBaltimore, MD\n(39.285066, -76.6..."
3550,229385,3RV727,11,13.0,MD,VOLV,1200 BOLTON ST,25,Less 30Â’ from Intersection,32.0,...,32.0,NaN,32.0,0.0,NaN,01/31/2018 08:34:00 PM,Bolton Hill,Central,11.0,"1200 BOLTON ST\nBaltimore, MD\n(39.304625, -76..."
3640,239038,7BX5561,04,16.0,MD,HOND,2010 BROENING HWY,26,No Stop/Park Handicap,502.0,...,0.0,NaN,0.0,0.0,11/04/2015,03/24/2016 04:02:00 AM,Canton Industrial Area,Southeastern,1.0,"2010 BROENING HWY\nBaltimore, MD\n(39.267502, ..."
3641,238022,5BA6882,04,13.0,MD,NISS,1700 MONTPELIER ST,3,Obstruct/Impeding Flow of Traffic,102.0,...,1127.0,NaN,102.0,672.0,04/24/2013,10/12/2016 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"1700 MONTPELIER ST\nBaltimore, MD\n(39.319815,..."
3663,239145,39855CH,04,18.0,MD,LEXUS,3716 BEEHLER AVE,5,Obstruct/Impeding Movement of Pedestrian,77.0,...,0.0,NaN,77.0,0.0,NaN,04/11/2018 04:02:00 AM,Central Park Heights,Northwestern,6.0,"3716 BEEHLER AVE\nBaltimore, MD\n(39.342319, -..."
4439,328633,AD46634,00,0.0,AR,FORD,1800 BOLTON ST,42,Commercial Vehicle Obstruct/Imped Traffic Flow,252.0,...,150.0,NaN,150.0,0.0,NaN,12/11/2012 04:04:00 AM,Bolton Hill,Central,11.0,"1800 BOLTON ST\nBaltimore, MD\n(39.309367, -76..."
4458,329250,8AZ907,12,12.0,MD,CHEV,1100 BOLTON ST,5,Obstruct/Impeding Movement of Pedestrian,77.0,...,77.0,NaN,77.0,0.0,NaN,01/31/2018 08:34:00 PM,Madison Park,Central,11.0,"1100 BOLTON ST\nBaltimore, MD\n(39.30354, -76...."
4597,349761,6AT0084,07,13.0,MD,TOYT,600 N PULASKI ST,19,Exceeding 48 Hours,32.0,...,332.0,NaN,32.0,300.0,02/05/2013,09/09/2014 04:02:00 AM,Midtown-Edmondson,Western,9.0,"600 N PULASKI ST\nBaltimore, MD\n(39.295454, -..."
4664,356055,2447572T,02,14.0,PA,HOND,1629 W NORTH AVE,12,No Stopping/Standing Not Tow-Away Zone,32.0,...,32.0,NaN,32.0,0.0,NaN,02/21/2014 04:02:00 AM,Penn North,Western,7.0,"1629 W NORTH AVE\nBaltimore, MD\n(39.310046, -..."
4734,362293,1AK4764,02,14.0,MD,CHEV,1500 APPLETON ST,3,Obstruct/Impeding Flow of Traffic,102.0,...,1127.0,NaN,102.0,761.0,12/19/2012,10/12/2016 04:02:00 AM,Easterwood,Western,7.0,"1500 APPLETON ST\nBaltimore, MD\n(39.30533, -7..."
4735,362566,4AM9647,01,14.0,MD,LEXUS,1501 APPLETON ST,17,Less Than 15 feet from Fire Hydrant,77.0,...,0.0,NaN,77.0,688.0,03/05/2013,10/12/2016 04:02:00 AM,Easterwood,Western,7.0,"1501 APPLETON ST\nBaltimore, MD\n(39.305313, -..."
4758,364455,XXN1568,10,11.0,NC,FORD,1561 WADSWORTH WAY,22,Expired Tags,32.0,...,332.0,NaN,32.0,300.0,12/31/2012,07/09/2014 04:02:00 AM,Loch Raven,Notheastern,4.0,"1561 WADSWORTH WAY\nBaltimore, MD\n(39.362992,..."
4802,365874,D83038,06,12.0,MD,NaN,300 E 30TH ST,11,Residential Parking Permit Only,52.0,...,552.0,NaN,52.0,500.0,09/18/2012,05/09/2015 04:01:00 AM,Abell,Northern,14.0,"300 E 30TH ST\nBaltimore, MD\n(39.324624, -76...."
5300,385336,3FZD57,05,12.0,MD,NISS,1800 N CAROLINE ST,22,Expired Tags,32.0,...,332.0,NaN,32.0,300.0,09/26/2012,04/09/2014 04:01:00 AM,Oliver,Eastern,12.0,"1800 N CAROLINE ST\nBaltimore, MD\n(39.310629,..."
5414,5461661,9CY4148,07,19.0,MD,HYUN,400 E BALTIMORE ST,46,No Parking/Standing In Bus Stop/Bus Lane,252.0,...,316.0,NaN,252.0,0.0,NaN,03/12/2019 04:03:00 AM,Downtown,Central,11.0,"(39.28997272, -76.61002178)"
5432,389304,2AT1088,08,13.0,MD,HOND,4300 NICHOLAS AVE,22,Expired Tags,32.0,...,357.0,NaN,32.0,300.0,10/01/2012,04/09/2014 04:01:00 AM,Belair-Edison,Notheastern,2.0,"4300 NICHOLAS AVE\nBaltimore, MD\n(39.327894, ..."
5436,389064,2MD1117,05,14.0,MD,VOLV,1509 BANK ST,22,Expired Tags,32.0,...,332.0,NaN,32.0,300.0,10/03/2012,05/09/2014 04:03:00 AM,Fells Point,Southeastern,1.0,"1509 BANK ST\nBaltimore, MD\n(39.286473, -76.5..."
5467,5461703,1CT4531,01,20.0,MD,HOND,200 N EUTAW ST,12,No Stopping/Standing Not Tow-Away Zone,32.0,...,96.0,NaN,32.0,0.0,NaN,03/12/2019 04:03:00 AM,Downtown,Central,11.0,"(39.29203643, -76.62180732)"
5498,392951,JLR240,05,15.0,MD,TOYT,400 E 33RD ST,12,No Stopping/Standing Not Tow-Away Zone,32.0,...,32.0,NaN,32.0,0.0,NaN,10/05/2013 04:04:00 AM,Oakenshawe,Northern,14.0,"400 E 33RD ST\nBaltimore, MD\n(39.328372, -76...."
5501,393454,97M678,08,15.0,MD,FORD,1600 CHILTON ST,10,"Commercial Veh/Residence under 20,000 lbs",252.0,...,0.0,NaN,0.0,0.0,NaN,02/04/2018 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"1600 CHILTON ST\nBaltimore, MD\n(39.327509, -7..."
5527,394155,1BF5281,09,15.0,MD,NISS,100 N LUZERNE AVE,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,525.0,10/23/2013,06/09/2016 04:02:00 AM,Patterson Park Neighborhood,Southeastern,1.0,"100 N LUZERNE AVE\nBaltimore, MD\n(39.293291, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3385186,97808415,4CK4945,07,16.0,MD,ACURA,2000 LINDEN AVE,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Reservoir Hill,Central,7.0,"2000 LINDEN AVE\nBaltimore, MD\n(39.311176, -7..."
3385187,97748272,5CM0925,09,16.0,MD,LINCO,2400 CALLOW AVE,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Reservoir Hill,Central,7.0,"2400 CALLOW AVE\nBaltimore, MD\n(39.314549, -7..."
3385188,97760665,5CG6841,03,17.0,MD,FORD,1800 BAKER ST,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Sandtown-Winchester,Western,7.0,"1800 BAKER ST\nBaltimore, MD\n(39.30662, -76.6..."
3385190,97748330,6CD5903,05,17.0,MD,CHEVR,2400 FRANCIS ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Penn North,Western,7.0,"2400 FRANCIS ST\nBaltimore, MD\n(39.311265, -7..."
3385191,97817366,8CG2815,04,17.0,MD,PONTI,800 APPLETON ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,Midtown-Edmondson,Western,9.0,"800 APPLETON ST\nBaltimore, MD\n(39.297892, -7..."
3385193,97759733,ACH689,05,17.0,MD,TOYOT,3200 BARCLAY ST,11,Residential Parking Permit Only,52.0,...,552.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,Abell,Northern,14.0,"3200 BARCLAY ST\nBaltimore, MD\n(39.327233, -7..."
3385195,97834981,7CH2118,05,18.0,MD,TOYOT,3000 GREENMOUNT AVE,8,No Stopping/Standing Tow Away Zone,52.0,...,577.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,Abell,Northern,14.0,"3000 GREENMOUNT AVE\nBaltimore, MD\n(39.324958..."
3385200,97825526,5CJ3792,07,17.0,MD,VOLKS,700 BARTLETT AVE,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,East Baltimore Midway,Eastern,12.0,"700 BARTLETT AVE\nBaltimore, MD\n(39.316109, -..."
3385205,97717970,2BL5561,12,16.0,MD,ACURA,2600 AISQUITH ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"2600 AISQUITH ST\nBaltimore, MD\n(39.31903, -7..."
3385207,97981097,9BN7663,07,17.0,MD,ACURA,3100 GREENMOUNT AVE,8,No Stopping/Standing Tow Away Zone,52.0,...,577.0,NaN,52.0,0.0,NaN,09/10/2016 04:02:00 AM,Abell,Northern,14.0,"3100 GREENMOUNT AVE\nBaltimore, MD\n(39.326252..."
3385211,97930144,0809Z0,03,18.0,MD,CHEVR,2900 MOSHER ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,Franklintown Road,Southwestern,9.0,"2900 MOSHER ST\nBaltimore, MD\n(39.299166, -76..."
3385217,97916713,8BG7823,04,16.0,MD,CADIL,2300 CALLOW AVE,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,16.0,09/14/2016,10/12/2016 04:02:00 AM,Reservoir Hill,Central,7.0,"2300 CALLOW AVE\nBaltimore, MD\n(39.313746, -7..."
3385221,97991450,5CD2575,10,16.0,MD,BUICK,2500 LAURETTA AVE,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,0.0,NaN,09/13/2016 04:02:00 AM,Rosemont Homeowners/Tenants,Western,9.0,"2500 LAURETTA AVE\nBaltimore, MD\n(39.294041, ..."
3385222,97928544,Z75017,11,17.0,MD,CHEVR,4000 OAKFORD AVE,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,0.0,NaN,09/10/2016 04:02:00 AM,West Arlington,Northwestern,6.0,"4000 OAKFORD AVE\nBaltimore, MD\n(39.335821, -..."
3385224,97987730,9CD8533,11,17.0,MD,NISSA,3200 GREENMOUNT AVE,8,No Stopping/Standing Tow Away Zone,52.0,...,577.0,NaN,52.0,0.0,NaN,09/10/2016 04:02:00 AM,Abell,Northern,14.0,"3200 GREENMOUNT AVE\nBaltimore, MD\n(39.327394..."
3385226,97994751,7BK0252,03,18.0,MD,CHEVR,5000 WABASH AVE,8,No Stopping/Standing Tow Away Zone,52.0,...,577.0,NaN,52.0,0.0,NaN,09/13/2016 04:02:00 AM,Dolfield,Northwestern,6.0,"5000 WABASH AVE\nBaltimore, MD\n(39.341626, -7..."
3385230,97931720,5BW2419,04,17.0,MD,HONDA,4000 EDMONDSON AVE,8,No Stopping/Standing Tow Away Zone,52.0,...,552.0,NaN,52.0,0.0,NaN,09/14/2016 04:02:00 AM,Edmondson Village,Southwestern,8.0,"4000 EDMONDSON AVE\nBaltimore, MD\n(39.29381, ..."
3385231,98021448,5CK1963,07,16.0,MD,FORD,2700 THE ALAMEDA,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,0.0,NaN,09/16/2016 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"2700 THE\nALAMEDA Baltimore, MD\n(35.030949, -..."
3385235,97968110,6BV7344,01,17.0,MD,TOYOT,300 WARREN AVE,11,Residential Parking Permit Only,52.0,...,525.0,NaN,52.0,16.0,09/21/2016,10/18/2016 04:01:00 AM,Federal Hill,Southern,11.0,"300 WARREN AVE\nBaltimore, MD\n(39.279055, -76..."
3385237,97997861,16459CG,04,17.0,MD,BMW,900 LIGHT ST,8,No Stopping/Standing Tow Away Zone,52.0,...,552.0,NaN,52.0,0.0,09/28/2016,09/29/2016 04:02:00 AM,Federal Hill,Southern,11.0,"900 LIGHT ST\nBaltimore, MD\n(39.278948, -76.6..."
3385238,97902879,7AA6866,12,16.0,MD,PONTI,800 LIGHT ST,8,No Stopping/Standing Tow Away Zone,52.0,...,502.0,NaN,52.0,0.0,NaN,09/24/2016 04:02:00 AM,Federal Hill,Southern,11.0,"800 LIGHT ST\nBaltimore, MD\n(39.279788, -76.6..."
3385241,97895024,4CG6630,05,18.0,MD,HONDA,2700 THE ALAMEDA,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,0.0,09/28/2016,09/29/2016 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"2700 THE\nALAMEDA Baltimore, MD\n(35.030949, -..."
3385243,97921168,6BF9322,12,17.0,MD,DODGE,2500 MCCULLOH ST,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,0.0,09/28/2016,09/29/2016 04:02:00 AM,Penn North,Western,7.0,"2500 MCCULLOH ST\nBaltimore, MD\n(39.313019, -..."
3385244,98005151,5BN7602,06,17.0,MD,JEEP,3718 CLAREMONT ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,0.0,NaN,09/24/2016 04:02:00 AM,Highlandtown,Southeastern,2.0,"3718 CLAREMONT ST\nBaltimore, MD\n(39.289487, ..."
3385247,98163612,9CM2854,10,16.0,MD,HYUND,1700 HOMESTEAD ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,0.0,NaN,10/13/2016 04:02:00 AM,Coldstream Homestead Montebello,Notheastern,14.0,"1700 HOMESTEAD ST\nBaltimore, MD\n(39.320347, ..."
3385252,97906870,948TBG,10,16.0,TN,JAGUA,4700 LOCH RAVEN BLVD,16,No Parking/Standing In Transit Stop,77.0,...,557.0,NaN,77.0,0.0,NaN,09/10/2016 04:02:00 AM,New Northwood,Notheastern,4.0,"4700 LOCH RAVEN BLVD\nBaltimore, MD\n(39.34785..."
3385255,98317325,8CJ0436,07,17.0,MD,NISSA,1200 OAKHURST PL,27,No Stop/Park Street Cleaning,52.0,...,552.0,NaN,52.0,0.0,NaN,10/18/2016 04:01:00 AM,Winchester,Southwestern,9.0,"1200 OAKHURST PL\nBaltimore, MD\n(39.301794, -..."
3385262,98321061,9CL2241,09,16.0,MD,FORD,2800 ROSALIND AVE,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,0.0,NaN,10/14/2016 04:02:00 AM,Cylburn,Northern,6.0,"2800 ROSALIND AVE\nBaltimore, MD\n(39.34593, -..."
3385266,98306641,5CF3889,02,18.0,MD,HYUND,1700 RUXTON AVE,27,No Stop/Park Street Cleaning,52.0,...,602.0,NaN,52.0,0.0,NaN,10/13/2016 04:02:00 AM,Coppin Heights/Ash-Co-East,Western,7.0,"1700 RUXTON AVE\nBaltimore, MD\n(39.307742, -7..."
3385267,98278832,8CL2458,09,17.0,MD,PONTI,3000 MCELDERRY ST,27,No Stop/Park Street Cleaning,52.0,...,577.0,NaN,52.0,0.0,NaN,10/13/2016 04:02:00 AM,Ellwood Park/Monument,Southeastern,13.0,"3000 MCELDERRY ST\nBaltimore, MD\n(39.298026, ..."

In [215]:
pol_dist = cite2['PoliceDistrict'].notna().sum()
pol_dist

345242

In [216]:
poldis_df = pol_dis.apply(lambda x: x.astype(str).str.lower())
poldis_df.dtypes
poldis_df['ViolFine'] = pd.to_numeric(poldis_df['ViolFine'])

In [217]:
poldis_vf = poldis_df.groupby('PoliceDistrict')['ViolFine'].mean()
pdvf = poldis_vf.to_frame()
pdvf.reset_index(0, inplace=True)
pdvf
#pdvf.columns = pdvf.columns.str.strip().str.replace(' ','')

  PoliceDistrict   ViolFine
0        central  44.816352
1        eastern  50.800873
2   northeastern  52.120643
3       northern  48.144727
4   northwestern  59.690660
5    notheastern  62.054571
6   southeastern  48.750365
7       southern  54.391261
8   southwestern  58.283804
9        western  53.526153

In [201]:
pdvf.groupby(['PoliceDistrict'].agg['ViolFine'].mean())

AttributeError: 'list' object has no attribute 'agg'

In [ ]:
if pdvf['PoliceDistrict']=="notheastern":

In [78]:
pol_dis_array = pol_dis.PoliceDistrict.value_counts()
pol_dis_array

Southeastern    63982
Central         58388
Southern        54643
Northern        42492
Notheastern     24592
Eastern         20743
Western         17886
Southwestern    15749
Northwestern    12859
SOUTHEASTERN     8600
SOUTHERN         7083
CENTRAL          6437
NORTHERN         5419
NORTHEASTERN     1865
EASTERN          1489
SOUTHWESTERN     1150
WESTERN          1137
NORTHWESTERN      728
Name: PoliceDistrict, dtype: int64

In [86]:
type(pol_dis_array)

pandas.core.series.Series

In [80]:
pol_dis_array.count()

18

In [184]:
dist_df = pol_dis_array.to_frame()
dist_df.index

Index(['Southeastern', 'Central', 'Southern', 'Northern', 'Notheastern',
       'Eastern', 'Western', 'Southwestern', 'Northwestern', 'SOUTHEASTERN',
       'SOUTHERN', 'CENTRAL', 'NORTHERN', 'NORTHEASTERN', 'EASTERN',
       'SOUTHWESTERN', 'WESTERN', 'NORTHWESTERN'],
      dtype='object')

In [185]:
dist_df.reset_index(0,inplace=True)

In [155]:
#dist_df.values
#[x * y - z for x, y, z in zip(df2['apples'], df2['oranges'], df2['bananas'])]
df2 = dist_df.apply(lambda x: x.astype(str).str.lower())
df2

           index PoliceDistrict
0   southeastern          63982
1        central          58388
2       southern          54643
3       northern          42492
4    notheastern          24592
5        eastern          20743
6        western          17886
7   southwestern          15749
8   northwestern          12859
9   southeastern           8600
10      southern           7083
11       central           6437
12      northern           5419
13  northeastern           1865
14       eastern           1489
15  southwestern           1150
16       western           1137
17  northwestern            728

In [156]:
df2.dtypes
df2['PoliceDistrict'] = pd.to_numeric(df2['PoliceDistrict'])

In [157]:
#df2.groupby(['index'])['PoliceDistrict'].sum().reset_index()
df2.groupby('index').sum()

              PoliceDistrict
index
central                64825
eastern                22232
northeastern            1865
northern               47911
northwestern           13587
notheastern            24592
southeastern           72582
southern               61726
southwestern           16899
western                19023

## Find the ten vehicle makes that received the most citations during 2017. For those top ten, find all Japanese-made vehicles. What proportion of all citations were written for those vehicles? Note that the naming in Make is not consistent over the whole dataset, so you will need to clean the data before calculating your answer. Your answer should be expressed as a decimal number (i.e. 0.42, not 42).

In [234]:
from datetime import datetime
cite2['year'] = pd.DatetimeIndex(cite2['ViolDate']).year
cite2.head()

,Citation,Tag,ExpMM,ExpYY,State,Make,Address,ViolCode,Description,ViolFine,...,PenaltyDate,OpenFine,OpenPenalty,NoticeDate,ImportDate,Neighborhood,PoliceDistrict,CouncilDistrict,Location,year
0,82691651,69943CF,04,19.0,MD,MAZD,1300 BLK EAST NORTHERN PKWY WB,32,Fixed Speed Camera,40.0,...,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"1300 BLK EAST NORTHERN PKWY\nWB Baltimore, MD\...",2018.0
1,85937226,T720887,12,18.0,MD,ACUR,300 BLK NORTH BEND RD SB,32,Fixed Speed Camera,40.0,...,NaN,0.0,0.0,NaN,01/03/2019 04:33:00 AM,NaN,NaN,NaN,NaN,2018.0
2,82691115,5BA2678,03,19.0,MD,TOYT,5000 BLK ROLAND AVE NB,32,Fixed Speed Camera,40.0,...,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"5000 BLK ROLAND AVE\nNB Baltimore, MD\n(39.353...",2018.0
3,82694689,5BT8544,01,18.0,MD,FORD,2400 BLK ERDMAN AVE NB,32,Fixed Speed Camera,40.0,...,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"2400 BLK ERDMAN AVE\nNB Baltimore, MD\n(39.325...",2018.0
4,82691214,1BV0537,11,18.0,MD,SUBA,1300 BLK WEST COLD SPRING LN W,32,Fixed Speed Camera,40.0,...,NaN,0.0,0.0,NaN,04/26/2018 04:02:00 AM,NaN,NaN,NaN,"1300 BLK WEST COLD SPRING LN W\nBaltimore, MD\...",2018.0

In [247]:
cite2['year'].dtype

dtype('float64')

In [248]:
cite_year2017 = cite2[cite2.year == 2017.0]
cite_year2017.head()

,Citation,Tag,ExpMM,ExpYY,State,Make,Address,ViolCode,Description,ViolFine,...,PenaltyDate,OpenFine,OpenPenalty,NoticeDate,ImportDate,Neighborhood,PoliceDistrict,CouncilDistrict,Location,year
631,50013862,7AC9218,01,19.0,MD,TOYT,E North AVE WB @ N Howard St,30,Red Light Violation,75.0,...,NaN,0.0,0.0,NaN,09/20/2017 04:03:00 AM,NaN,NaN,NaN,"E N North AVE WB\nBaltimore, MD",2017.0
676,50097410,2EYW11,04,19.0,MD,HOND,Loch Raven Blvd NB @ E Belvede,30,Red Light Violation,75.0,...,NaN,0.0,0.0,NaN,10/21/2017 04:02:00 AM,NaN,NaN,NaN,"E Loch Raven Blvd NB\nBaltimore, MD",2017.0
698,50129379,LB0393,00,0.0,MD,MERZ,Loch Raven Blvd SB @ E Belvede,30,Red Light Violation,75.0,...,NaN,0.0,0.0,NaN,10/31/2017 04:02:00 AM,NaN,NaN,NaN,"E Loch Raven Blvd SB\nBaltimore, MD",2017.0
703,50131359,5BP5889,00,0.0,MD,FORD,Pulaski Hwy EB @ N North Point,30,Red Light Violation,75.0,...,NaN,0.0,0.0,NaN,10/31/2017 04:02:00 AM,NaN,NaN,NaN,"N Pulaski Hwy EB\nBaltimore, MD",2017.0
726,50151134,3CY2133,00,0.0,MD,NISS,Pulaski Hwy EB @ Moravia Park,30,Red Light Violation,75.0,...,NaN,0.0,0.0,NaN,11/03/2017 04:02:00 AM,NaN,NaN,NaN,"Pulaski Hwy EB\nBaltimore, MD",2017.0

In [261]:
cite_year2017.Make.mode()

0    FORD
dtype: object

In [299]:
top2017 = cite_year2017.groupby(['year', 'Make']).year.value_counts().nlargest(10)
top2017df = top2017.to_frame()
top2017df
# top2017df.set_index(['Make'], inplace=True, append = True, drop = True)

                      year
year   Make  year
2017.0 FORD  2017.0  56786
       HONDA 2017.0  43049
       TOYOT 2017.0  40844
       NISSA 2017.0  27991
       CHEVR 2017.0  27745
       TOYT  2017.0  27590
       HOND  2017.0  27368
       NISS  2017.0  22014
       CHEV  2017.0  21705
       JEEP  2017.0  16973

In [271]:
totalcite17 = cite_year2017.year.value_counts().sum()
totalcite17

553981

In [304]:
japcars = 43049+40844+27991+27590+27368+22014
japcars

188856

In [305]:
japcars/totalcite17

0.34090699861547596

In [314]:
cite2yrs = cite2.groupby(['year']).sum()
cite2yrs.reset_index(level=0, inplace=True)
cite2yrs

,year,Citation,ExpYY,ViolCode,ViolFine,Balance,PenaltyDate,OpenFine,OpenPenalty,CouncilDistrict
0,1999.0,40231789,0.0,30,75.0,0.0,0.0,0.0,0.0,0.0
1,2000.0,123437109,5.0,90,225.0,0.0,0.0,0.0,0.0,0.0
2,2002.0,2553370481,267.0,1740,4350.0,0.0,0.0,0.0,0.0,0.0
3,2003.0,6787273770,671.0,4440,11100.0,0.0,0.0,0.0,0.0,0.0
4,2004.0,5929909208,1142.0,3860,7985.0,8240.0,0.0,3673.0,2155.0,58.0
5,2005.0,40143341317,7438.0,23573,44565.0,50852.0,0.0,40655.0,4870.0,510.0
6,2006.0,325847089541,39841.0,128173,204672.0,255737.0,0.0,196211.0,3570.0,2094.0
7,2007.0,3274128266047,381597.0,1138640,1915819.0,2252863.0,0.0,1903316.0,23343.0,40565.0
8,2008.0,2730980171881,356333.0,884699,1579975.0,1817096.0,0.0,1561574.0,12030.0,57745.0
9,2009.0,2936647980524,404338.0,889395,1653234.0,1842377.0,0.0,1608374.0,228185.0,58937.0
10,2010.0,3728444379924,481453.0,967703,1973124.0,2131881.0,0.0,1927679.0,159457.0,82724.0
11,2011.0,10805799688122,1482399.0,3676969,6358346.0,18331275.0,0.0,6272580.0,13322533.0,92867.0
12,2012.0,6763628192955,1939530.0,4609708,7843721.0,18421078.0,0.0,7001911.0,12521072.0,106336.0
13,2013.0,1718882502872,720176.0,1186059,2889470.0,12884423.0,0.0,2220923.0,11615391.0,89305.0
14,2014.0,4256522079363,1148855.0,1643654,4210955.0,12887230.0,0.0,2308770.0,11035398.0,133480.0
15,2015.0,31470855699741,5485300.0,7132276,16373563.0,13275068.0,0.0,2830878.0,8163712.0,510376.0
16,2016.0,32644033406144,5726222.0,7099195,16751740.0,13700476.0,0.0,8148758.0,2581124.0,510976.0
17,2017.0,39607232779820,9391396.0,13838616,26824551.0,14185941.0,0.0,16542725.0,8381.0,498856.0
18,2018.0,67556368178499,17808057.0,27291887,51001756.0,20300833.0,0.0,17193296.0,0.0,502637.0
19,2019.0,37667975559146,10319129.0,15539944,29054786.0,15411914.0,0.0,7084232.0,0.0,196541.0

In [317]:
cite2_2004to2014 = cite2yrs.loc[(cite2yrs['year'] >= 2004.0) & (cite2yrs['year'] <= 2014.0)]
cite2_2004to2014

,year,Citation,ExpYY,ViolCode,ViolFine,Balance,PenaltyDate,OpenFine,OpenPenalty,CouncilDistrict
4,2004.0,5929909208,1142.0,3860,7985.0,8240.0,0.0,3673.0,2155.0,58.0
5,2005.0,40143341317,7438.0,23573,44565.0,50852.0,0.0,40655.0,4870.0,510.0
6,2006.0,325847089541,39841.0,128173,204672.0,255737.0,0.0,196211.0,3570.0,2094.0
7,2007.0,3274128266047,381597.0,1138640,1915819.0,2252863.0,0.0,1903316.0,23343.0,40565.0
8,2008.0,2730980171881,356333.0,884699,1579975.0,1817096.0,0.0,1561574.0,12030.0,57745.0
9,2009.0,2936647980524,404338.0,889395,1653234.0,1842377.0,0.0,1608374.0,228185.0,58937.0
10,2010.0,3728444379924,481453.0,967703,1973124.0,2131881.0,0.0,1927679.0,159457.0,82724.0
11,2011.0,10805799688122,1482399.0,3676969,6358346.0,18331275.0,0.0,6272580.0,13322533.0,92867.0
12,2012.0,6763628192955,1939530.0,4609708,7843721.0,18421078.0,0.0,7001911.0,12521072.0,106336.0
13,2013.0,1718882502872,720176.0,1186059,2889470.0,12884423.0,0.0,2220923.0,11615391.0,89305.0
14,2014.0,4256522079363,1148855.0,1643654,4210955.0,12887230.0,0.0,2308770.0,11035398.0,133480.0

# Question II

In [226]:
import math
import os
import random
import re
import sys
from collections import deque

class Point():
    def __init__(self, x, y, count):
        self.x = x
        self.y = y
        self.count = count


def checkBound(curP, a, b, n, check, myQ):
    X, Y = curP.x, curP.y

    if (X - a) >= 0:
        if (Y - b) >= 0 and check[X-a][Y-b] == 0:
            myQ.append(Point(X-a, Y-b, curP.count+1))
            check[X-a][Y-b] = 1
        if (Y + b) < n and check[X-a][Y+b] == 0:
            myQ.append(Point(X-a, Y+b, curP.count+1))
            check[X-a][Y+b] = 1
    if (X + a) < n:
        if (Y - b) >= 0 and check[X+a][Y-b] == 0:
            myQ.append(Point(X+a, Y-b, curP.count+1))
            check[X+a][Y-b] = 1
        if (Y + b) < n and check[X+a][Y+b] == 0:
            myQ.append(Point(X+a, Y+b, curP.count+1))
            check[X+a][Y+b] = 1
            if (X + a) == n-1 and (Y + b) == n-1:
                return curP.count + 1   ##Check for the target point
    return -1


def step(n, a, b):
    myQ = deque()
    check = [[0]*n for i in range(n)]  ##Check whether this point is visited or not

    start = Point(0, 0, 0)
    check[start.x][start.y] = 1
    myQ.append(start)

    while len(myQ) > 0:
        curP = myQ.popleft()
        count1 = checkBound(curP, a, b, n, check, myQ)
        count2 = checkBound(curP, b, a, n, check, myQ)
        if count1 > 0 or count2 > 0: 
            return max(count1, count2)

    return -1

print(step(1000,13,23))

def knightlOnAChessboard(n):
    res = [[0]*(n-1) for i in range(n-1)]
    for i in range(n-1):
        for j in range(i, n-1):
            res[i][j] = step(n, i+1, j+1)

    for i in range(1, n-1):
        for j in range(i):
            res[i][j] = res[j][i]

    return res

print(knightlOnAChessboard(5))

67
[[4, 4, 2, 8], [4, 2, 4, 4], [2, 4, -1, -1], [8, 4, -1, 1]]